### ISSUE TITLE
Reverse Engineered?

### ISSUE THREAD

**Issue by aryan-f** [JimWest/PyLiveLinkFace#1]
Hi there.

I was just wondering, if you have reversed engineered the existing iOS app in order to extract the structure of UDP packets, the `FaceBlendShape` enums, etc. I couldn't find anything explaining these values in the UE4 documentation.

Thank you.

**Comment by JimWest** [comment]
At first, I have captured the udp packages with wireshark and reversed engineered the bits and bytes, looking which are changing, which are not (fortunately the IPhone also sends packages when no faces are in the image, so it was easy to identify which bits are the actual blendshapes). You can also show the actual value of the blendshape arraving in the Unreal Engine. 

Then I found this, which helped me with the enum:
https://docs.unrealengine.com/4.26/en-US/API/Runtime/AugmentedReality/EARFaceBlendShape/

At the end I found this which gave me everything I needed: https://github.com/EpicGames/UnrealEngine/blob/4.26.2-release/Engine/Plugins/Runtime/AR/AppleAR/AppleARKitFaceSupport/Source/AppleARKitFaceSupport/Private/AppleARKitLiveLinkSource.cpp

**Comment by aryan-f** [comment]
Thanks a bunch!
