### ISSUE TITLE
consider not using --no_filter=False by default. 

### ISSUE THREAD

**Issue by rohitdavas** [JimWest/PyLiveLinkFace#3]
Hi, after working with your code, i came to realise that the py_face.set_blendshape api has no_filter = False by default. 

It would be a better option to consider not using filter. 
Why ? 

- py_live_link face should serve as linker, not processor. It gives less option, but precise use case api for user. often the default parameters are supposed to be left untouched, which brings the issue of mistakes, and not getting the exact results. 

e.g I didn't bother to check the default parameters, and lead to the case that i thought unreal is doing post processing. 

- leaving filter implementation is better choice, as it leads to separation of concerns. 

However these are my views. I would be happy to read what you guys think.

And, thanks for great work. Simplified the life of many.

**Comment by JimWest** [comment]
Hi, yeah that's a good Idea, I've merged your pull request.
